apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-write
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Hola, això està escrit automàticament al PVC." > /data/escrit-des-del-pod.txt;
        date >> /data/escrit-des-del-pod.txt;
        echo "Fitxer creat i escrit. Ara dormo indefinidament...";
        sleep 3600
    volumeMounts:
    - mountPath: /data
      name: mypvc
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName: nfs-pvc-test
